//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 03:43:34 PM EEST 
//


package ats.mpc.cstmrreg_26;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsDefAcctRes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GrpHdr">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text"/>
 *                             &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrgnlMsgId" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
 *                             &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrgnlMsgSts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.26.01}ResponseStatus"/>
 *                             &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.26.01}Max10Text"/>
 *                             &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Rply" type="{urn:ats:mpc:cstmrreg.26.01}Max1Text" minOccurs="0"/>
 *                   &lt;element name="RgstrtnCd" type="{urn:ats:mpc:cstmrreg.26.01}Max10Text" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isDefAcctRes"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "IsDefAcctRes", required = true)
    protected Document.IsDefAcctRes isDefAcctRes;

    /**
     * Gets the value of the isDefAcctRes property.
     * 
     * @return
     *     possible object is
     *     {@link Document.IsDefAcctRes }
     *     
     */
    public Document.IsDefAcctRes getIsDefAcctRes() {
        return isDefAcctRes;
    }

    /**
     * Sets the value of the isDefAcctRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.IsDefAcctRes }
     *     
     */
    public void setIsDefAcctRes(Document.IsDefAcctRes value) {
        this.isDefAcctRes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GrpHdr">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text"/>
     *                   &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrgnlMsgId" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
     *                   &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrgnlMsgSts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.26.01}ResponseStatus"/>
     *                   &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.26.01}Max10Text"/>
     *                   &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Rply" type="{urn:ats:mpc:cstmrreg.26.01}Max1Text" minOccurs="0"/>
     *         &lt;element name="RgstrtnCd" type="{urn:ats:mpc:cstmrreg.26.01}Max10Text" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grpHdr",
        "orgnlMsgId",
        "orgnlMsgSts",
        "rply",
        "rgstrtnCd"
    })
    public static class IsDefAcctRes {

        @XmlElement(name = "GrpHdr", required = true)
        protected Document.IsDefAcctRes.GrpHdr grpHdr;
        @XmlElement(name = "OrgnlMsgId")
        protected Document.IsDefAcctRes.OrgnlMsgId orgnlMsgId;
        @XmlElement(name = "OrgnlMsgSts", required = true)
        protected Document.IsDefAcctRes.OrgnlMsgSts orgnlMsgSts;
        @XmlElement(name = "Rply")
        protected String rply;
        @XmlElement(name = "RgstrtnCd")
        protected String rgstrtnCd;

        /**
         * Gets the value of the grpHdr property.
         * 
         * @return
         *     possible object is
         *     {@link Document.IsDefAcctRes.GrpHdr }
         *     
         */
        public Document.IsDefAcctRes.GrpHdr getGrpHdr() {
            return grpHdr;
        }

        /**
         * Sets the value of the grpHdr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.IsDefAcctRes.GrpHdr }
         *     
         */
        public void setGrpHdr(Document.IsDefAcctRes.GrpHdr value) {
            this.grpHdr = value;
        }

        /**
         * Gets the value of the orgnlMsgId property.
         * 
         * @return
         *     possible object is
         *     {@link Document.IsDefAcctRes.OrgnlMsgId }
         *     
         */
        public Document.IsDefAcctRes.OrgnlMsgId getOrgnlMsgId() {
            return orgnlMsgId;
        }

        /**
         * Sets the value of the orgnlMsgId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.IsDefAcctRes.OrgnlMsgId }
         *     
         */
        public void setOrgnlMsgId(Document.IsDefAcctRes.OrgnlMsgId value) {
            this.orgnlMsgId = value;
        }

        /**
         * Gets the value of the orgnlMsgSts property.
         * 
         * @return
         *     possible object is
         *     {@link Document.IsDefAcctRes.OrgnlMsgSts }
         *     
         */
        public Document.IsDefAcctRes.OrgnlMsgSts getOrgnlMsgSts() {
            return orgnlMsgSts;
        }

        /**
         * Sets the value of the orgnlMsgSts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.IsDefAcctRes.OrgnlMsgSts }
         *     
         */
        public void setOrgnlMsgSts(Document.IsDefAcctRes.OrgnlMsgSts value) {
            this.orgnlMsgSts = value;
        }

        /**
         * Gets the value of the rply property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRply() {
            return rply;
        }

        /**
         * Sets the value of the rply property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRply(String value) {
            this.rply = value;
        }

        /**
         * Gets the value of the rgstrtnCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRgstrtnCd() {
            return rgstrtnCd;
        }

        /**
         * Sets the value of the rgstrtnCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRgstrtnCd(String value) {
            this.rgstrtnCd = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text"/>
         *         &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "msgId",
            "creDtTm"
        })
        public static class GrpHdr {

            @XmlElement(name = "MsgId", required = true)
            protected String msgId;
            @XmlElement(name = "CreDtTm", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creDtTm;

            /**
             * Gets the value of the msgId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgId() {
                return msgId;
            }

            /**
             * Sets the value of the msgId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgId(String value) {
                this.msgId = value;
            }

            /**
             * Gets the value of the creDtTm property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreDtTm() {
                return creDtTm;
            }

            /**
             * Sets the value of the creDtTm property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreDtTm(XMLGregorianCalendar value) {
                this.creDtTm = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
         *         &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.26.01}Max35Text" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "msgTp"
        })
        public static class OrgnlMsgId {

            @XmlElement(name = "Id")
            protected String id;
            @XmlElement(name = "MsgTp")
            protected String msgTp;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the msgTp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgTp() {
                return msgTp;
            }

            /**
             * Sets the value of the msgTp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgTp(String value) {
                this.msgTp = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.26.01}ResponseStatus"/>
         *         &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.26.01}Max10Text"/>
         *         &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sts",
            "rsnCd",
            "nrtn"
        })
        public static class OrgnlMsgSts {

            @XmlElement(name = "Sts", required = true)
            protected ResponseStatus sts;
            @XmlElement(name = "RsnCd", required = true)
            protected String rsnCd;
            @XmlElement(name = "Nrtn")
            protected String nrtn;

            /**
             * Gets the value of the sts property.
             * 
             * @return
             *     possible object is
             *     {@link ResponseStatus }
             *     
             */
            public ResponseStatus getSts() {
                return sts;
            }

            /**
             * Sets the value of the sts property.
             * 
             * @param value
             *     allowed object is
             *     {@link ResponseStatus }
             *     
             */
            public void setSts(ResponseStatus value) {
                this.sts = value;
            }

            /**
             * Gets the value of the rsnCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRsnCd() {
                return rsnCd;
            }

            /**
             * Sets the value of the rsnCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRsnCd(String value) {
                this.rsnCd = value;
            }

            /**
             * Gets the value of the nrtn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNrtn() {
                return nrtn;
            }

            /**
             * Sets the value of the nrtn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNrtn(String value) {
                this.nrtn = value;
            }

        }

    }

}
