//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 03:43:34 PM EEST 
//


package ats.mpc.cstmrreg_20;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ats.mpc.cstmrreg_20 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ats.mpc.cstmrreg_20
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.CstmrNameReq }
     * 
     */
    public Document.CstmrNameReq createDocumentCstmrNameReq() {
        return new Document.CstmrNameReq();
    }

    /**
     * Create an instance of {@link Document.CstmrNameReq.GrpHdr }
     * 
     */
    public Document.CstmrNameReq.GrpHdr createDocumentCstmrNameReqGrpHdr() {
        return new Document.CstmrNameReq.GrpHdr();
    }

}
