//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 03:43:34 PM EEST 
//


package ats.mpc.cstmrreg_21;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CstmrNameRes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GrpHdr">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text"/>
 *                             &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrgnlMsgId" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
 *                             &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrgnlMsgSts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.21.01}ResponseStatus"/>
 *                             &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.21.01}Max10Text"/>
 *                             &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CstmrNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CstmrTp" type="{urn:ats:mpc:cstmrreg.21.01}Max10Text" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cstmrNameRes"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "CstmrNameRes", required = true)
    protected Document.CstmrNameRes cstmrNameRes;

    /**
     * Gets the value of the cstmrNameRes property.
     * 
     * @return
     *     possible object is
     *     {@link Document.CstmrNameRes }
     *     
     */
    public Document.CstmrNameRes getCstmrNameRes() {
        return cstmrNameRes;
    }

    /**
     * Sets the value of the cstmrNameRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.CstmrNameRes }
     *     
     */
    public void setCstmrNameRes(Document.CstmrNameRes value) {
        this.cstmrNameRes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GrpHdr">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text"/>
     *                   &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrgnlMsgId" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
     *                   &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrgnlMsgSts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.21.01}ResponseStatus"/>
     *                   &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.21.01}Max10Text"/>
     *                   &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CstmrNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CstmrTp" type="{urn:ats:mpc:cstmrreg.21.01}Max10Text" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grpHdr",
        "orgnlMsgId",
        "orgnlMsgSts",
        "cstmrNm",
        "cstmrTp"
    })
    public static class CstmrNameRes {

        @XmlElement(name = "GrpHdr", required = true)
        protected Document.CstmrNameRes.GrpHdr grpHdr;
        @XmlElement(name = "OrgnlMsgId")
        protected Document.CstmrNameRes.OrgnlMsgId orgnlMsgId;
        @XmlElement(name = "OrgnlMsgSts", required = true)
        protected Document.CstmrNameRes.OrgnlMsgSts orgnlMsgSts;
        @XmlElement(name = "CstmrNm")
        protected String cstmrNm;
        @XmlElement(name = "CstmrTp")
        protected String cstmrTp;

        /**
         * Gets the value of the grpHdr property.
         * 
         * @return
         *     possible object is
         *     {@link Document.CstmrNameRes.GrpHdr }
         *     
         */
        public Document.CstmrNameRes.GrpHdr getGrpHdr() {
            return grpHdr;
        }

        /**
         * Sets the value of the grpHdr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.CstmrNameRes.GrpHdr }
         *     
         */
        public void setGrpHdr(Document.CstmrNameRes.GrpHdr value) {
            this.grpHdr = value;
        }

        /**
         * Gets the value of the orgnlMsgId property.
         * 
         * @return
         *     possible object is
         *     {@link Document.CstmrNameRes.OrgnlMsgId }
         *     
         */
        public Document.CstmrNameRes.OrgnlMsgId getOrgnlMsgId() {
            return orgnlMsgId;
        }

        /**
         * Sets the value of the orgnlMsgId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.CstmrNameRes.OrgnlMsgId }
         *     
         */
        public void setOrgnlMsgId(Document.CstmrNameRes.OrgnlMsgId value) {
            this.orgnlMsgId = value;
        }

        /**
         * Gets the value of the orgnlMsgSts property.
         * 
         * @return
         *     possible object is
         *     {@link Document.CstmrNameRes.OrgnlMsgSts }
         *     
         */
        public Document.CstmrNameRes.OrgnlMsgSts getOrgnlMsgSts() {
            return orgnlMsgSts;
        }

        /**
         * Sets the value of the orgnlMsgSts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.CstmrNameRes.OrgnlMsgSts }
         *     
         */
        public void setOrgnlMsgSts(Document.CstmrNameRes.OrgnlMsgSts value) {
            this.orgnlMsgSts = value;
        }

        /**
         * Gets the value of the cstmrNm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCstmrNm() {
            return cstmrNm;
        }

        /**
         * Sets the value of the cstmrNm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCstmrNm(String value) {
            this.cstmrNm = value;
        }

        /**
         * Gets the value of the cstmrTp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCstmrTp() {
            return cstmrTp;
        }

        /**
         * Sets the value of the cstmrTp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCstmrTp(String value) {
            this.cstmrTp = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text"/>
         *         &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "msgId",
            "creDtTm"
        })
        public static class GrpHdr {

            @XmlElement(name = "MsgId", required = true)
            protected String msgId;
            @XmlElement(name = "CreDtTm", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creDtTm;

            /**
             * Gets the value of the msgId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgId() {
                return msgId;
            }

            /**
             * Sets the value of the msgId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgId(String value) {
                this.msgId = value;
            }

            /**
             * Gets the value of the creDtTm property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreDtTm() {
                return creDtTm;
            }

            /**
             * Sets the value of the creDtTm property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreDtTm(XMLGregorianCalendar value) {
                this.creDtTm = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
         *         &lt;element name="MsgTp" type="{urn:ats:mpc:cstmrreg.21.01}Max35Text" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "msgTp"
        })
        public static class OrgnlMsgId {

            @XmlElement(name = "Id")
            protected String id;
            @XmlElement(name = "MsgTp")
            protected String msgTp;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the msgTp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgTp() {
                return msgTp;
            }

            /**
             * Sets the value of the msgTp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgTp(String value) {
                this.msgTp = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Sts" type="{urn:ats:mpc:cstmrreg.21.01}ResponseStatus"/>
         *         &lt;element name="RsnCd" type="{urn:ats:mpc:cstmrreg.21.01}Max10Text"/>
         *         &lt;element name="Nrtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sts",
            "rsnCd",
            "nrtn"
        })
        public static class OrgnlMsgSts {

            @XmlElement(name = "Sts", required = true)
            protected ResponseStatus sts;
            @XmlElement(name = "RsnCd", required = true)
            protected String rsnCd;
            @XmlElement(name = "Nrtn")
            protected String nrtn;

            /**
             * Gets the value of the sts property.
             * 
             * @return
             *     possible object is
             *     {@link ResponseStatus }
             *     
             */
            public ResponseStatus getSts() {
                return sts;
            }

            /**
             * Sets the value of the sts property.
             * 
             * @param value
             *     allowed object is
             *     {@link ResponseStatus }
             *     
             */
            public void setSts(ResponseStatus value) {
                this.sts = value;
            }

            /**
             * Gets the value of the rsnCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRsnCd() {
                return rsnCd;
            }

            /**
             * Sets the value of the rsnCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRsnCd(String value) {
                this.rsnCd = value;
            }

            /**
             * Gets the value of the nrtn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNrtn() {
                return nrtn;
            }

            /**
             * Sets the value of the nrtn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNrtn(String value) {
                this.nrtn = value;
            }

        }

    }

}
