//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 03:43:34 PM EEST 
//


package ats.mpc.cstmrreg_25;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsDefAcctReq">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GrpHdr">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
 *                             &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PrtcpntId" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
 *                   &lt;element name="MblOrSvc" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
 *                   &lt;element name="RgstrtnCd" type="{urn:ats:mpc:cstmrreg.25.01}Max10Text" minOccurs="0"/>
 *                   &lt;element name="AcntTp" type="{urn:ats:mpc:cstmrreg.25.01}Max1Text" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isDefAcctReq"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "IsDefAcctReq", required = true)
    protected Document.IsDefAcctReq isDefAcctReq;

    /**
     * Gets the value of the isDefAcctReq property.
     * 
     * @return
     *     possible object is
     *     {@link Document.IsDefAcctReq }
     *     
     */
    public Document.IsDefAcctReq getIsDefAcctReq() {
        return isDefAcctReq;
    }

    /**
     * Sets the value of the isDefAcctReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Document.IsDefAcctReq }
     *     
     */
    public void setIsDefAcctReq(Document.IsDefAcctReq value) {
        this.isDefAcctReq = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GrpHdr">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
     *                   &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PrtcpntId" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
     *         &lt;element name="MblOrSvc" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
     *         &lt;element name="RgstrtnCd" type="{urn:ats:mpc:cstmrreg.25.01}Max10Text" minOccurs="0"/>
     *         &lt;element name="AcntTp" type="{urn:ats:mpc:cstmrreg.25.01}Max1Text" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grpHdr",
        "prtcpntId",
        "mblOrSvc",
        "rgstrtnCd",
        "acntTp"
    })
    public static class IsDefAcctReq {

        @XmlElement(name = "GrpHdr", required = true)
        protected Document.IsDefAcctReq.GrpHdr grpHdr;
        @XmlElement(name = "PrtcpntId", required = true)
        protected String prtcpntId;
        @XmlElement(name = "MblOrSvc", required = true)
        protected String mblOrSvc;
        @XmlElement(name = "RgstrtnCd")
        protected String rgstrtnCd;
        @XmlElement(name = "AcntTp")
        protected String acntTp;

        /**
         * Gets the value of the grpHdr property.
         * 
         * @return
         *     possible object is
         *     {@link Document.IsDefAcctReq.GrpHdr }
         *     
         */
        public Document.IsDefAcctReq.GrpHdr getGrpHdr() {
            return grpHdr;
        }

        /**
         * Sets the value of the grpHdr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document.IsDefAcctReq.GrpHdr }
         *     
         */
        public void setGrpHdr(Document.IsDefAcctReq.GrpHdr value) {
            this.grpHdr = value;
        }

        /**
         * Gets the value of the prtcpntId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrtcpntId() {
            return prtcpntId;
        }

        /**
         * Sets the value of the prtcpntId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrtcpntId(String value) {
            this.prtcpntId = value;
        }

        /**
         * Gets the value of the mblOrSvc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMblOrSvc() {
            return mblOrSvc;
        }

        /**
         * Sets the value of the mblOrSvc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMblOrSvc(String value) {
            this.mblOrSvc = value;
        }

        /**
         * Gets the value of the rgstrtnCd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRgstrtnCd() {
            return rgstrtnCd;
        }

        /**
         * Sets the value of the rgstrtnCd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRgstrtnCd(String value) {
            this.rgstrtnCd = value;
        }

        /**
         * Gets the value of the acntTp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcntTp() {
            return acntTp;
        }

        /**
         * Sets the value of the acntTp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcntTp(String value) {
            this.acntTp = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MsgId" type="{urn:ats:mpc:cstmrreg.25.01}Max35Text"/>
         *         &lt;element name="CreDtTm" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "msgId",
            "creDtTm"
        })
        public static class GrpHdr {

            @XmlElement(name = "MsgId", required = true)
            protected String msgId;
            @XmlElement(name = "CreDtTm", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creDtTm;

            /**
             * Gets the value of the msgId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgId() {
                return msgId;
            }

            /**
             * Sets the value of the msgId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgId(String value) {
                this.msgId = value;
            }

            /**
             * Gets the value of the creDtTm property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreDtTm() {
                return creDtTm;
            }

            /**
             * Sets the value of the creDtTm property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreDtTm(XMLGregorianCalendar value) {
                this.creDtTm = value;
            }

        }

    }

}
