//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.08 at 03:43:34 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ats:mpc:cstmrreg.25.01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ats.mpc.cstmrreg_25;
